# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CatalogOfMovies_OMDb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CatalogOfMovies_OMDb
  pod ‘Alamofire’
  pod ‘JSONJoy-Swift’

  target 'CatalogOfMovies_OMDbTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CatalogOfMovies_OMDbUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
